# Generated by Django 5.2.6 on 2025-10-13 22:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pelicula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('anio', models.IntegerField()),
                ('director', models.CharField(max_length=255)),
                ('imagen_url', models.URLField()),
                ('trailer_url', models.URLField()),
                ('generos', models.CharField(max_length=255)),
                ('horarios', models.CharField(blank=True, max_length=255, null=True)),
                ('salas', models.CharField(blank=True, max_length=255, null=True)),
                ('clasificacion', models.CharField(choices=[('APT', 'APT'), ('13+', '13+'), ('18+', '18+')], default='APT', max_length=20)),
                ('idioma', models.CharField(choices=[('Español', 'Español'), ('Inglés subtitulado', 'Inglés subtitulado'), ('Inglés', 'Inglés')], default='Español', max_length=50)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'peliculas',
            },
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_cliente', models.CharField(max_length=100)),
                ('apellido_cliente', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('formato', models.CharField(choices=[('2D', '2D - $3.50'), ('3D', '3D - $4.50'), ('IMAX', 'IMAX - $6.00')], max_length=4)),
                ('sala', models.CharField(max_length=50)),
                ('horario', models.CharField(max_length=50)),
                ('asientos', models.CharField(max_length=255)),
                ('cantidad_boletos', models.PositiveIntegerField(default=1)),
                ('precio_total', models.DecimalField(decimal_places=2, max_digits=6)),
                ('estado', models.CharField(choices=[('RESERVADO', 'Reservado'), ('CONFIRMADO', 'Confirmado'), ('CANCELADO', 'Cancelado')], default='RESERVADO', max_length=10)),
                ('fecha_reserva', models.DateTimeField(auto_now_add=True)),
                ('codigo_reserva', models.CharField(max_length=10, unique=True)),
                ('usado', models.BooleanField(default=False)),
                ('pelicula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.pelicula')),
            ],
            options={
                'verbose_name': 'Reserva',
                'verbose_name_plural': 'Reservas',
                'db_table': 'reservas',
            },
        ),
        migrations.CreateModel(
            name='Valoracion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(1, '1 estrella'), (2, '2 estrellas'), (3, '3 estrellas'), (4, '4 estrellas'), (5, '5 estrellas')])),
                ('resena', models.TextField(blank=True, help_text='Escribe tu reseña (opcional, máximo 500 caracteres)', max_length=500, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('pelicula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valoraciones', to='myapp.pelicula')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Valoración',
                'verbose_name_plural': 'Valoraciones',
                'ordering': ['-fecha_creacion'],
                'unique_together': {('pelicula', 'usuario')},
            },
        ),
    ]
