# Generated by Django 5.2.7 on 2025-10-17 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodigoDescuento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('porcentaje', models.DecimalField(decimal_places=2, max_digits=5)),
                ('estado', models.BooleanField(default=True)),
            ],
        ),
    ]
