# Generated by Django 5.2.6 on 2025-10-13 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pelicula',
            name='fecha_estreno',
            field=models.DateField(blank=True, null=True),
        ),
    ]
