# Generated by Django 5.2.6 on 2025-10-14 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_pelicula_fecha_estreno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pelicula',
            name='clasificacion',
            field=models.CharField(choices=[('APT', 'APT'), ('13+', '13+'), ('18+', '18+')], default='APT', max_length=30),
        ),
    ]
