# Generated by Django 5.2.5 on 2025-09-04 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_reserva'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pelicula',
            name='director',
            field=models.CharField(max_length=350),
        ),
        migrations.AlterField(
            model_name='pelicula',
            name='generos',
            field=models.CharField(max_length=350),
        ),
        migrations.AlterField(
            model_name='pelicula',
            name='horarios',
            field=models.CharField(blank=True, max_length=350, null=True),
        ),
        migrations.AlterField(
            model_name='pelicula',
            name='nombre',
            field=models.CharField(max_length=350),
        ),
        migrations.AlterField(
            model_name='pelicula',
            name='salas',
            field=models.CharField(blank=True, max_length=350, null=True),
        ),
    ]
