# Generated by Django 5.2.5 on 2025-10-15 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_pelicula_clasificacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pelicula',
            name='clasificacion',
            field=models.CharField(choices=[('APT', 'APT (Todo Publico)'), ('13+', '13+ (Mayores de 13 anos)'), ('18+', '18+')], default='APT', max_length=10),
        ),
        migrations.AlterField(
            model_name='pelicula',
            name='idioma',
            field=models.CharField(choices=[('ESP', 'Español'), ('ING', 'Ingles Sub Titulado'), ('SUB', 'Inglés')], default='ESP', max_length=30),
        ),
    ]
