# Generated by Django 5.2.5 on 2025-10-20 16:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_funcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pelicula',
            name='clasificacion',
            field=models.CharField(choices=[('APT', 'Todo Publico'), ('13+', 'Mayores de 13 años'), ('18+', 'Solo Adultos')], default='APT', max_length=10),
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sala', models.CharField(max_length=50)),
                ('fecha', models.DateField()),
                ('cantidad_boletos', models.PositiveIntegerField()),
                ('total_venta', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pelicula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.pelicula')),
            ],
        ),
    ]
