# Generated by Django 5.2.5 on 2025-09-04 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_pelicula_director_alter_pelicula_generos_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pelicula',
            name='imagen_url',
            field=models.URLField(max_length=600),
        ),
        migrations.AlterField(
            model_name='pelicula',
            name='trailer_url',
            field=models.URLField(max_length=600),
        ),
    ]
