# Generated by Django 5.2.5 on 2025-09-04 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_pelicula_imagen_url_alter_pelicula_trailer_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pelicula',
            name='imagen_url',
            field=models.URLField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='pelicula',
            name='trailer_url',
            field=models.URLField(max_length=1000),
        ),
    ]
