# Generated by Django 5.2.7 on 2025-11-01 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_reserva_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pelicula',
            name='clasificacion',
            field=models.CharField(choices=[('APT', 'Todo Público'), ('13+', 'Mayores de 13 años'), ('18+', 'Solo Adultos')], default='APT', max_length=10),
        ),
        migrations.AlterField(
            model_name='pelicula',
            name='idioma',
            field=models.CharField(choices=[('ESP', 'Español'), ('SUB', 'Inglés Subtitulado'), ('ING', 'Inglés')], default='ESP', max_length=30),
        ),
    ]
