# Generated by Django 5.2.6 on 2025-09-07 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_pelicula_imagen_url_alter_pelicula_trailer_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='usado',
            field=models.BooleanField(default=False),
        ),
    ]
