# Generated by Django 5.2.7 on 2025-11-01 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_pelicula_clasificacion_alter_pelicula_idioma'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pelicula',
            name='horarios',
        ),
    ]
