# Generated by Django 5.2.6 on 2025-09-13 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_reserva_usado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pelicula',
            name='director',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='pelicula',
            name='generos',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='pelicula',
            name='horarios',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='pelicula',
            name='imagen_url',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='pelicula',
            name='nombre',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='pelicula',
            name='salas',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='pelicula',
            name='trailer_url',
            field=models.URLField(),
        ),
    ]
