# Generated by Django 5.2.7 on 2025-11-01 23:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_remove_pelicula_horarios'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='funcion',
            options={'ordering': ['fecha_inicio', 'horario']},
        ),
        migrations.RemoveField(
            model_name='funcion',
            name='fecha',
        ),
        migrations.AddField(
            model_name='funcion',
            name='fecha_inicio',
            field=models.DateField(blank=True, help_text='Fecha de inicio de la programación', null=True),
        ),
        migrations.AddField(
            model_name='funcion',
            name='semanas',
            field=models.PositiveIntegerField(default=1, help_text='Duración en semanas (1–8)'),
        ),
        migrations.AlterField(
            model_name='funcion',
            name='horario',
            field=models.CharField(choices=[('10:00', '10:00'), ('10:30', '10:30'), ('11:00', '11:00'), ('11:30', '11:30'), ('12:00', '12:00'), ('12:30', '12:30'), ('13:00', '1:00 PM'), ('13:30', '1:30 PM'), ('14:00', '2:00 PM'), ('14:30', '2:30 PM'), ('15:00', '3:00 PM'), ('15:30', '3:30 PM'), ('16:00', '4:00 PM'), ('16:30', '4:30 PM'), ('17:00', '5:00 PM'), ('17:30', '5:30 PM'), ('18:00', '6:00 PM'), ('18:30', '6:30 PM'), ('19:00', '7:00 PM'), ('19:30', '7:30 PM')], max_length=5),
        ),
        migrations.AlterField(
            model_name='funcion',
            name='pelicula',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='funciones', to='myapp.pelicula'),
        ),
    ]
