# Generated by Django 5.2.5 on 2025-09-14 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_alter_pelicula_director_alter_pelicula_generos_and_more'),
        ('myapp', '0008_valoracion'),
    ]

    operations = [
    ]
