# Generated by Django 5.2.5 on 2025-10-13 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_merge_20250914_1609'),
    ]

    operations = [
        migrations.AddField(
            model_name='pelicula',
            name='fecha_estreno',
            field=models.DateField(blank=True, help_text='Fecha de estreno (opcional)', null=True),
        ),
    ]
