# Generated by Django 5.2.7 on 2025-11-01 23:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_alter_funcion_horario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='funcion',
            name='formato',
        ),
    ]
