# Generated by Django 5.2.7 on 2025-11-02 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_limpiar_salas_funciones'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcion',
            name='activa',
            field=models.BooleanField(default=True, help_text='Si la función sigue activa'),
        ),
        migrations.AddField(
            model_name='funcion',
            name='fecha_eliminacion',
            field=models.DateField(blank=True, help_text='Fecha en que se eliminó la función', null=True),
        ),
    ]
