# Generated by Django 5.2.7 on 2025-11-02 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_funcion_activa_funcion_fecha_eliminacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='fecha_funcion',
            field=models.DateField(blank=True, help_text='Fecha de la función reservada', null=True),
        ),
    ]
