# Generated by Django 5.2.5 on 2025-11-05 03:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_reserva_fecha_funcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='fecha_pago',
            field=models.DateTimeField(blank=True, help_text='Fecha y hora en que se completó el pago', null=True),
        ),
        migrations.AddField(
            model_name='reserva',
            name='pago_completado',
            field=models.BooleanField(default=False, help_text='Indica si el pago fue completado'),
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=8)),
                ('metodo_pago', models.CharField(choices=[('TARJETA', 'Tarjeta de Crédito/Débito'), ('CUENTA_DIGITAL', 'Cuenta Digital')], max_length=20)),
                ('estado_pago', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('APROBADO', 'Aprobado'), ('RECHAZADO', 'Rechazado'), ('REEMBOLSADO', 'Reembolsado')], default='PENDIENTE', max_length=15)),
                ('fecha_pago', models.DateTimeField(auto_now_add=True)),
                ('numero_transaccion', models.CharField(help_text='Número único de transacción', max_length=50, unique=True)),
                ('detalles_pago', models.JSONField(blank=True, help_text='Información adicional del pago', null=True)),
                ('reserva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='myapp.reserva')),
            ],
            options={
                'verbose_name': 'Pago',
                'verbose_name_plural': 'Pagos',
                'db_table': 'pagos',
                'ordering': ['-fecha_pago'],
            },
        ),
    ]
