# Generated by Django 5.2.5 on 2025-11-06 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_reserva_fecha_pago_reserva_pago_completado_pago'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='pago_completado',
            field=models.BooleanField(blank=True, default=False, help_text='Indica si el pago fue completado', null=True),
        ),
    ]
