# Generated by Django 5.2.5 on 2025-11-06 03:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_alter_reserva_pago_completado'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MetodoPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('TARJETA', 'Tarjeta de Crédito/Débito'), ('CUENTA_DIGITAL', 'Cuenta Digital')], max_length=20)),
                ('alias', models.CharField(help_text="Nombre personalizado para este método (ej: 'Visa Personal')", max_length=50)),
                ('es_predeterminado', models.BooleanField(default=False, help_text='Método de pago predeterminado')),
                ('activo', models.BooleanField(default=True, help_text='Si el método está activo o fue eliminado')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('ultimos_4_digitos', models.CharField(blank=True, help_text='Últimos 4 dígitos de la tarjeta', max_length=4, null=True)),
                ('tipo_tarjeta', models.CharField(blank=True, choices=[('VISA', 'Visa'), ('MASTERCARD', 'Mastercard'), ('AMEX', 'American Express'), ('DISCOVER', 'Discover'), ('OTRO', 'Otro')], max_length=15, null=True)),
                ('mes_expiracion', models.IntegerField(blank=True, help_text='Mes de expiración (1-12)', null=True)),
                ('anio_expiracion', models.IntegerField(blank=True, help_text='Año de expiración (YYYY)', null=True)),
                ('nombre_titular', models.CharField(blank=True, max_length=100, null=True)),
                ('tipo_cuenta', models.CharField(blank=True, choices=[('PAYPAL', 'PayPal'), ('STRIPE', 'Stripe'), ('OTRO', 'Otro')], max_length=20, null=True)),
                ('email_cuenta', models.EmailField(blank=True, max_length=254, null=True)),
                ('datos_encriptados', models.TextField(blank=True, help_text='Datos sensibles encriptados', null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metodos_pago', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Método de Pago',
                'verbose_name_plural': 'Métodos de Pago',
                'db_table': 'metodos_pago',
                'ordering': ['-es_predeterminado', '-fecha_creacion'],
                'unique_together': {('usuario', 'alias')},
            },
        ),
    ]
