# Generated by Django 5.2.5 on 2025-11-07 03:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0019_alter_pago_reserva'),
    ]

    operations = [
        migrations.AddField(
            model_name='pago',
            name='metodo_pago_guardado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagos_realizados', to='myapp.metodopago'),
        ),
    ]
