# Generated by Django 5.2.7 on 2025-11-09 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0020_pago_metodo_pago_guardado'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='formato',
            field=models.CharField(choices=[('2D', '2D'), ('3D', '3D'), ('IMAX', 'IMAX'), ('4DX', '4DX')], default='2D', max_length=10),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='formato',
            field=models.CharField(choices=[('2D', '2D - $4.00'), ('3D', '3D - $6.00'), ('IMAX', 'IMAX - $8.00')], max_length=4),
        ),
    ]
