# Generated by Django 5.2.7 on 2025-11-10 03:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0021_venta_formato_alter_reserva_formato'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='fecha_venta',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
